name: Build

on:
  push:
    tags:
      - "v*.*.*"

  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheel for ${{ matrix.platform[1] }}_${{ matrix.platform[2] }}

    runs-on: ${{ matrix.platform[0] }}
    strategy:
      matrix:
        platform:
          - [ubuntu-22.04, manylinux, x86_64]
          - [ubuntu-22.04, musllinux, x86_64]
          - [macos-12, macosx, x86_64]
          - [macos-12, macosx, arm64]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build wheel
        uses: pypa/cibuildwheel@v2.12.1
        env:
          CIBW_ARCHS: ${{ matrix.platform[2] }}
          CIBW_BUILD: cp*-${{ matrix.platform[1] }}_${{ matrix.platform[2] }}
          CIBW_SKIP: "cp36* cp37*"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build sdist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Build sdist
        run: python setup.py sdist

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ./dist/*
